### ISSUE TITLE
add process scanning?

### ISSUE THREAD

**Issue by CanadaHonk** [OpenAsar/arrpc#16]
undecided on whether to add or not as it isn't really RPC but loosely related (not in `discord_rpc` but in `discord_game_utils` for Discord's own Native modules, for example). would expand the scope quite a bit but might be worth it. **please react/comment if you want!** it would be optional/disableable if added to eliminate privacy/etc concerns.

**Comment by CanadaHonk** [comment]
Will be out in v3 with verified/detectable games only, using Discord's "database" (JSON file from API). Good for privacy as all Discord actually sees is the name and id of a game if recognised, not any/all processes. Only limitation is that it's verified/detectable only and just sets activity, UI is still disabled in web/etc.

**Comment by CanadaHonk** [comment]
v3 has released featuring process scanning!

**Comment by bagusnl** [comment]
sorry to come in on quite an old thread, but is there any way to disable process scanning done by arRPC so it only relies on other means of RPC like game SDK and stuff?
Asked this because the original thread mentioned `it would be optional/disableable if added to eliminate privacy/etc concerns.` yet I have not been able to find the guide to disable it on the Readme

Currently using arRPC standalone server running as a service using NSSM and Node v20.5.0 while using Vesktop as the client

**Comment by CanadaHonk** [comment]
I forgot lol. Just added in 3e22fd7; you can now use the `--no-process-scanning` argument or the `ARRPC_NO_PROCESS_SCANNING` env variable.

**Comment by bagusnl** [comment]
alrighty thank you
