### ISSUE TITLE
support other platforms for process scanning

### ISSUE THREAD

**Issue by CanadaHonk** [OpenAsar/arrpc#19]

**Comment by japa4551** [comment]
That would be marvelous! Wish i had the $ to sponsor arRPC for this feature.

Discord Rich Presence does not work at all on Linux Systems (because they dont want to) due to 90% of the games being run through a Compatibility Layer like Wine or Proton, something like this would really help the community.

**Comment by CanadaHonk** [comment]
Linux and Mac now scan for compatible games (using Discord's DB).
